language: node_js
node_js:
  - "5"
  - "4.4.2"
cache: bundler

services:
  - docker

before_install:
  - rvm install 2.2.2
  - gem install bundler
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm cache clean
  - docker build --tag travis .
  - docker run -d -p 127.0.0.1:8080:8080 -e NODE_ENV=ci travis

script:
  -  npm run test:ci && npm run test:acceptance
