---
Kb8Context:
  cluster: dsp-dev
  user: formsso.ci
  namespace: gro-form-preprod

Fn::FileData:
- name: tls_tag
  files:
  - ../../artefacts/tls_tag
- name: app_tag
  files:
  - ../../artefacts/app_tag
- name: redis_tag
  files:
  - ../../artefacts/redis_tag
- name: tls_key
  encode: base64
  files:
  - ../secrets/preprod/gro-form-key
- name: tls_crt
  encode: base64
  files:
  - ../secrets/preprod/gro-form-crt

GRO_HTTP_PORT: 30243
GRO_HTTPS_PORT: 30244
